WITH MAX_FISH AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT ID, NAME.FISH_NAME, LENGTH
FROM FISH_INFO AS INFO
INNER JOIN MAX_FISH AS MF
ON INFO.FISH_TYPE = MF.FISH_TYPE
    AND INFO.LENGTH = MF.MAX_LENGTH
INNER JOIN FISH_NAME_INFO AS NAME
ON INFO.FISH_TYPE = NAME.FISH_TYPE
