SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS INFO
INNER JOIN FISH_NAME_INFO AS NAME
ON INFO.FISH_TYPE = NAME.FISH_TYPE
WHERE INFO.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO
    WHERE FISH_TYPE = INFO.FISH_TYPE
)
