WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA AS PARENT
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT CHILD.ID, CHILD.PARENT_ID, C.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA AS CHILD
    INNER JOIN CTE AS C
    ON CHILD.PARENT_ID = C.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM CTE
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM CTE
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
