SELECT CAR.CAR_ID, CAR.CAR_TYPE, ROUND(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
ON CAR.CAR_TYPE = PLAN.CAR_TYPE
WHERE CAR.CAR_TYPE IN ('세단', 'SUV')
    AND PLAN.DURATION_TYPE = '30일 이상'
    AND CAR.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
    AND DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100 >= 500000
    AND DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100 < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
