SELECT P3.ID
FROM ECOLI_DATA AS P3
INNER JOIN (
    SELECT P1.ID AS P1_ID, P2.ID AS P2_ID
    FROM ECOLI_DATA AS P2
    INNER JOIN (
        SELECT *
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL
    ) AS P1
    ON P1.ID = P2.PARENT_ID
) AS P4
ON P3.PARENT_ID = P4.P2_ID
